---
- name: Configure the web server(s) according to specs
  hosts: web
  become: true
  roles:
    - base
    - webserver

- name: Configure the database server(s) according to specs
  hosts: db
  become: true
  roles:
    - base
    - dbserver
