---
- name: Install MariaDB-server
  hosts: db
  become: true
  tasks:
    - name: Ensure MariaDB-server is installed.
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB-server is started at boot
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true
