---
- name: Copies local files from host to webserver
  hosts: web
  become: true
  tasks:
    - name: Define source and destination paths
      ansible.builtin.copy:
        src: files/https.conf
        dest: /etc/nginx/conf.d
        mode: '0644'
        owner: root
        group: root

    - name: Ensure the nginx configuration is updated for example.internal
      ansible.builtin.template:
        src: templates/example.internal.conf.j2
        dest: /etc/nginx/conf.d/example.internal.conf
        mode: '0644'
        owner: root
        group: root

    - name: Create directory structure for website
      ansible.builtin.file:
        path: /var/www/example.internal/html/
        state: directory
        mode: '0755'

    - name: Upload html file to website directory
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/example.internal/html/index.html
        mode: '0644'
      register: result

    - name: Print the value of result
      ansible.builtin.debug:
        var: result

    - name: Ensure Nginx is restarted  # noqa no-handler
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: result.changed
